/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 8;
  int ABSTRACT = 10;
  int BOOLEAN = 11;
  int CHAR = 12;
  int CLASS = 13;
  int ELSE = 14;
  int EXTENDS = 15;
  int FALSE = 16;
  int IF = 17;
  int IMPORT = 18;
  int INSTANCEOF = 19;
  int INT = 20;
  int NEW = 21;
  int NULL = 22;
  int PACKAGE = 23;
  int PRIVATE = 24;
  int PROTECTED = 25;
  int PUBLIC = 26;
  int RETURN = 27;
  int STATIC = 28;
  int SUPER = 29;
  int THIS = 30;
  int TRUE = 31;
  int VOID = 32;
  int WHILE = 33;
  int BREAK = 34;
  int BYTE = 35;
  int CASE = 36;
  int CATCH = 37;
  int CONST = 38;
  int CONTINUE = 39;
  int DEF = 40;
  int DO = 41;
  int DOUBLE = 42;
  int FINAL = 43;
  int FINALLY = 44;
  int FLOAT = 45;
  int FOR = 46;
  int GOTO = 47;
  int IMPLEMENTS = 48;
  int INTERFACE = 49;
  int LONG = 50;
  int NATIVE = 51;
  int SHORT = 52;
  int STRICTFP = 53;
  int SWITCH = 54;
  int SYNC = 55;
  int THROW = 56;
  int THROWS = 57;
  int TRANSIENT = 58;
  int TRY = 59;
  int VOLATILE = 60;
  int PLUS = 61;
  int ASSIGN = 62;
  int DEC = 63;
  int EQUAL = 64;
  int GT = 65;
  int INC = 66;
  int LAND = 67;
  int LE = 68;
  int LNOT = 69;
  int MINUS = 70;
  int PLUS_ASSIGN = 71;
  int STAR = 72;
  int B_AND = 73;
  int B_AND_ASSIGN = 74;
  int B_COMP = 75;
  int B_OR = 76;
  int B_OR_ASSIGN = 77;
  int B_XOR = 78;
  int B_XOR_ASSIGN = 79;
  int CONDITIONAL = 80;
  int DIV = 81;
  int DIV_ASSIGN = 82;
  int GE = 83;
  int LOR = 84;
  int LT = 85;
  int MINUS_ASSIGN = 86;
  int NOT_EQUAL = 87;
  int REM = 88;
  int REM_ASSIGN = 89;
  int SL_SHIFT = 90;
  int SL_SHIFT_ASSIGN = 91;
  int SR_SHIFT = 92;
  int SR_SHIFT_ASSIGN = 93;
  int STAR_ASSIGN = 94;
  int UR_SHIFT = 95;
  int UR_SHIFT_ASSIGN = 96;
  int LPAREN = 97;
  int RPAREN = 98;
  int LCURLY = 99;
  int RCURLY = 100;
  int LBRACK = 101;
  int RBRACK = 102;
  int SEMI = 103;
  int COMMA = 104;
  int DOT = 105;
  int COL = 106;
  int IDENTIFIER = 107;
  int LETTER = 108;
  int DIGIT = 109;
  int NON_ZERO_DIGIT = 110;
  int INT_LITERAL = 111;
  int DOUBLE_LITERAL = 112;
  int CHAR_LITERAL = 113;
  int STRING_LITERAL = 114;
  int ESC = 115;
  int ERROR = 116;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"implements\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"short\"",
    "\"strictfp\"",
    "\"switch\"",
    "\"synchonized\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"try\"",
    "\"volatile\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"&\"",
    "\"&=\"",
    "\"~\"",
    "\"|\"",
    "\"|=\"",
    "\"^\"",
    "\"^=\"",
    "\"?\"",
    "\"/\"",
    "\"/=\"",
    "\">=\"",
    "\"||\"",
    "\"<\"",
    "\"-=\"",
    "\"!=\"",
    "\"%\"",
    "\"%=\"",
    "\"<<\"",
    "\"<<=\"",
    "\">>\"",
    "\">>=\"",
    "\"*=\"",
    "\">>>\"",
    "\">>>=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
